name: Test

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: GitHub Slug
      uses: rlespinasse/github-slug-action@1.1.0
    - name: Print slug variables
      run: |
        echo ${{ env.GITHUB_REF_SLUG }}
        echo ${{ env.GITHUB_HEAD_REF_SLUG }}
        echo ${{ env.GITHUB_BASE_REF_SLUG }}
        echo ${{ env.GITHUB_SHA_SHORT }}
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Generate changelog
        uses: charmixer/auto-changelog-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/upload-artifact@v1
        with:
          name: changelog
          path: ./CHANGELOG.md
