name: Test

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - name: GitHub Slug
      uses: rlespinasse/github-slug-action@1.1.0
    - name: Print slug variables
      run: |
        echo ${{ env.GITHUB_REF_SLUG }}
        echo ${{ env.GITHUB_HEAD_REF_SLUG }}
        echo ${{ env.GITHUB_BASE_REF_SLUG }}
        echo ${{ env.GITHUB_SHA_SHORT }}
  release:
    name: Release binaries with goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
      
      - name: GitHub Slug
        uses: rlespinasse/github-slug-action@1.1.0

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Generate release changelog
        uses: charmixer/auto-changelog-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG-RELEASE.md
          since_tag: ${{ steps.previoustag.outputs.tag }}
          due_tag: ${{ env.GITHUB_REF_SLUG }}
          
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v1
        with:
          version: latest
          args: release --rm-dist --release-notes=CHANGELOG-RELEASE.md
          # key: ${{ secrets.YOUR_PRIVATE_KEY }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
